global:
  scrape_interval:     10s
  evaluation_interval: 10s
scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'telegraf'
    static_configs:
    - targets: ['172.17.0.1:9273'] # Adjust the IP address to match your host's IP if necessary docker

  - job_name: 'gatewayTelegraf'
    static_configs:
    - targets: ['165.99.148.50:9273'] # Adjust the IP address to match your host's IP if necessary docker

remote_write:
  - url: "http://promscale:9201/write"
remote_read:
  - url: "http://promscale:9201/read"
    read_recent: true


